export const LOAD_BLOGS_DISPATCH = "LOAD_BLOGS_DISPATCH";
export const LOAD_BLOGS_SUCCESS = "LOAD_BLOGS_SUCCESS";
export const LOAD_BLOGS_ERROR = "LOAD_BLOGS_ERROR";

export const ADD_BLOG_DISPATCH = "ADD_BLOG_DISPATCH";
export const ADD_BLOG_SUCCESS = "ADD_BLOG_SUCCESS";
export const ADD_BLOG_ERROR = "ADD_BLOG_ERROR";
